const saudacoes = [
    { termo: "Pai Oxalá", explicacao: "Êepa Babá" },
    { termo: "Xangô", explicacao: "Kao Kabecile (Salve o Rei)" },
    { termo: "Ibeji", explicacao: "Oni Beijada" },
    { termo: "Iemanjá", explicacao: "Odociaba ou Odoyá" },
    { termo: "Oxum", explicacao: "Aiêiê Omin" },
    { termo: "Iansã", explicacao: "Eparrei Iansã" },
    { termo: "Nanã Buruquê", explicacao: "Saluba Nanã" },
    { termo: "Oxóssi", explicacao: "Okê Bambiocline / Okê Arô" },
    { termo: "Ogum", explicacao: "Ogum Iê" },
    { termo: "Obaluaê / Omolu", explicacao: "Atotô" },
    { termo: "São Miguel e Pretos-Velhos", explicacao: "Adorei as Almas" },
    { termo: "Marinheiro", explicacao: "Aruba Marinheiro" },
    { termo: "Boiadeiro", explicacao: "Epachê Boiadeiro, Arubachê, Getruá" },
    { termo: "Povo Cigano", explicacao: "Optchá" },
    { termo: "Povo do Oriente", explicacao: "Ori Osorium" },
    { termo: "Exu", explicacao: "Laroyê" },
    { termo: "Tranca Rua", explicacao: "Aleluia ou Onoluia" },
    { termo: "Bará", explicacao: "Moju Bará" }
];